frigate:
  image:
    repository: docker.io/blakeblackshear/frigate
    tag: 0.11.1
  securityContext:
    privileged: true
  
  persistence:
    data:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 10Gi
      mountPath: /data
    media:
      enabled: true
      existingClaim: nas-media-pvc
      mountPath: /media
      subPath: Videos
    # usb:
    #   enabled: true
    #   type: hostPath
    #   hostPath: /dev/bus/usb
    cache:
      enabled: true
      type: emptyDir
      medium: Memory
      sizeLimit: 2Gi
      # mountPath: /dev/shm
      mountPath: /tmp/cache


# affinity:
#     nodeAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#         nodeSelectorTerms:
#           - matchExpressions:
#               - key: feature.node.kubernetes.io/custom-coral-tpu
#                 operator: In
#                 values:
#                   - "true"
#   resources:
#     requests:
#       memory: 1000Mi
#       cpu: 750m
#       gpu.intel.com/i915: 1
#     limits:
#       memory: 2000Mi
#       gpu.intel.com/i915: 1

  env:
    TZ: "Europe/Berlin"

  configmap:
    config:
      enabled: true
      data:
        config.yml: |
          mqtt:
            host: emqx.homelab.svc
            topic_prefix: frigate
            user: mqtt
            password: '{FRIGATE_MQTT_PASSWORD}'

          database:
            path: /data/frigate.db
          
          ffmpeg:
            global_args:
              - -hide_banner
              - -loglevel
              - warning
            hwaccel_args:
              - -hwaccel
              - vaapi
              - -hwaccel_device
              - /dev/dri/renderD128
              - -hwaccel_output_format
              - yuv420p
            output_args:
              record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac -ar 44100
              rtmp: -c:v copy -f flv -ar 44100 -c:a aac
          
          objects:
            track:
              - person
          
          record:
            enabled: true
            retain:
              days: 0
              mode: motion
            events:
              retain:
                default: 14
                mode: active_objects
          
          cameras:
            kitchen:
              ffmpeg:
                inputs:
                  - path: 'rtsp://172.18.18.240/live0'
                    roles:
                      - detect
              detect:
                height: 480
                width: 704
                fps: 5
              objects:
                filters:
                  person:
                    min_area: 1500
                    max_area: 100000
                    threshold: 0.75
                    min_score: 0.60

  valuesFrom:
  - kind: Secret
    name: "frigate-values"
    optional: false