longhorn:
  persistence:
    defaultClassReplicaCount: 2
  defaultSettings:
    defaultReplicaCount: 2
    createDefaultDiskLabeledNodes: true
    backupstorePollInterval: 300
    defaultDataLocality: best-effort
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    concurrentAutomaticEngineUpgradePerNodeLimit: 1
    defaultDataPath: /var/lib/longhorn
    replicaSoftAntiAffinity: false
    storageMinimalAvailablePercentage: 10
  # ingress:
  #   enabled: true
  #   host: longhorn.local.ibartels.de
  #   tlsSecret: local.ibartels.de-tls
  #   tls: true
  #   annotations:
  #     kubernetes.io/ingress.class: nginx