emqx:
  replicaCount: 2
  recreatePods: true
  # service:
  #   type: LoadBalancer
  #   loadBalancerIP: 172.18.18.33
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - emqx
          topologyKey: "kubernetes.io/hostname"
  emqxConfig:
    EMQX_ALLOW_ANONYMOUS: "true"

  emqxAclConfig: >
    {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
    {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
    {allow, all, subscribe, ["$SYS/#", {eq, "#"}]}.
    {allow, all}.
  emqxLoadedPlugins: >
    {emqx_management, true}.
    {emqx_recon, true}.
    {emqx_retainer, true}.
    {emqx_dashboard, true}.
    {emqx_telemetry, false}.
    {emqx_rule_engine, true}.
    {emqx_bridge_mqtt, true}.
    {emqx_auth_mnesia, true}.
   # {emqx_prometheus, true}.
  emqxLoadedModules: >
    {emqx_mod_presence, true}.
    {emqx_mod_delayed, false}.
    {emqx_mod_rewrite, false}.
    {emqx_mod_subscription, false}.
    {emqx_mod_topic_metrics, true}.
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 150Mi

#   ingress:
#     dashboard:
#       enabled: true
#       annotations:
#         kubernetes.io/ingress.class: nginx
#       path: /
#       hosts:
#         - emqx.local.ibartels.de
#       tls:
#         - hosts:
#             - emqx.local.ibartels.de
#           secretName: local.ibartels.de-tls
# valuesFrom:
#   - kind: Secret
#     name: "emqx-secretss"
#     optional: false