nfs-subdir-external-provisioner:
  nfs:
    server: "172.18.18.80"
    path: "/volume2/k3s-storage/test"
    mountOptions:
      - noatime
  storageClass:
    defaultClass: false
    pathPattern: "${.PVC.namespace}-${.PVC.name}"
