argo-cd:
  installCRDs: false
  global:
    image:
      repository: argoproj/argocd
#      tag: v2.2.3
  dex:
    enabled: false

  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2
      targetCPUUtilizationPercentage: 85
      targetMemoryUtilizationPercentage: 85

    # volumeMounts:
    #   - name: helm-values
    #     mountPath: /helm-values
    # volumes:
    #   - name: helm-values
    #     secret:
    #       secretName: argo-helm-values
    #       optional: true
    # resources:
    #   requests:
    #     cpu: 5526m
    #     memory: 4744M

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - argocd-repo-server
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - argocd
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - repo-server
            topologyKey: "kubernetes.io/hostname"
  server:
    service:
      type: NodePort
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: git
          url: https://github.com/Puller23/home-ops-test.git
          passwordSecret:
            name: deployment-git-repo-credentials
            key: password
          usernameSecret:
            name: deployment-git-repo-credentials
            key: username
# Following the guide at https://argoproj.github.io/argo-cd/user-guide/diffing/#system-level-configuration
      resource.customizations: |
        admissionregistration.k8s.io/MutatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/clientConfig/caBundle
# metrics:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true
    # autoscaling:
    #   enabled: true
    #   minReplicas: 2
    #   targetCPUUtilizationPercentage: 85
    #   targetMemoryUtilizationPercentage: 85
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 105Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - argocd-server
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - argocd
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - server
            topologyKey: "kubernetes.io/hostname"
  controller:
    extraArgs:
    - --repo-server-timeout-seconds
    - "500"
    - --status-processors
    - "10"
    - --operation-processors
    - "5"
  repoServer:
    replicas: 2
    env:
      - name: "ARGOCD_EXEC_TIMEOUT"
        value: "5m"

  redis:
    image:
      repository: redis
      tag: 6.2.6-alpine
